"""empty message

Revision ID: 17fc36c5005a
Revises: cff84ec6324a
Create Date: 2023-11-16 00:58:57.323045

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '17fc36c5005a'
down_revision = 'cff84ec6324a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('good', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Img_id', sa.String(length=100), nullable=False))
        batch_op.drop_column('foto_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('good', schema=None) as batch_op:
        batch_op.add_column(sa.Column('foto_id', sa.VARCHAR(length=100), nullable=False))
        batch_op.drop_column('Img_id')

    # ### end Alembic commands ###
