"""empty message

Revision ID: 99eeaddc264c
Revises: a051f98cfad7
Create Date: 2023-11-09 13:07:42.440908

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '99eeaddc264c'
down_revision = 'a051f98cfad7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('about_me')
        batch_op.drop_column('last_seen')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_seen', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('about_me', sa.VARCHAR(length=140), nullable=True))

    # ### end Alembic commands ###
