"""empty message

Revision ID: cff84ec6324a
Revises: fb0acfb7106a
Create Date: 2023-11-16 00:13:52.415710

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cff84ec6324a'
down_revision = 'fb0acfb7106a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('good', schema=None) as batch_op:
        batch_op.add_column(sa.Column('foto_id', sa.String(length=100), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('good', schema=None) as batch_op:
        batch_op.drop_column('foto_id')

    # ### end Alembic commands ###
