"""empty message

Revision ID: fb0acfb7106a
Revises: 38ffc7a0111f
Create Date: 2023-11-15 23:49:36.854043

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fb0acfb7106a'
down_revision = '38ffc7a0111f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('basket', schema=None) as batch_op:
        batch_op.add_column(sa.Column('size', sa.Integer(), nullable=False))

    with op.batch_alter_table('good', schema=None) as batch_op:
        batch_op.drop_column('f_price')
        batch_op.drop_column('size')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('good', schema=None) as batch_op:
        batch_op.add_column(sa.Column('size', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('f_price', sa.FLOAT(), nullable=False))

    with op.batch_alter_table('basket', schema=None) as batch_op:
        batch_op.drop_column('size')

    # ### end Alembic commands ###
