"""empty message

Revision ID: fb174eaf65b8
Revises: 17fc36c5005a
Create Date: 2023-11-16 01:28:52.656634

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fb174eaf65b8'
down_revision = '17fc36c5005a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('good', schema=None) as batch_op:
        batch_op.alter_column('price',
               existing_type=sa.FLOAT(),
               type_=sa.Integer(),
               existing_nullable=False)
        batch_op.alter_column('discount',
               existing_type=sa.FLOAT(),
               type_=sa.Integer(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('good', schema=None) as batch_op:
        batch_op.alter_column('discount',
               existing_type=sa.Integer(),
               type_=sa.FLOAT(),
               existing_nullable=False)
        batch_op.alter_column('price',
               existing_type=sa.Integer(),
               type_=sa.FLOAT(),
               existing_nullable=False)

    # ### end Alembic commands ###
